### ISSUE TITLE
buildConfigField：NEWS_API_KEY

### ISSUE THREAD

**Issue by Catherinelhl** [AkshayChordiya/android-arch-news-sample#11] opened 2018-03-21 02:12 UTC
There is a problem:Could not get unknown property "NEWS_API_KEY" for DefaultConfig_Decorated{.....;how to solve it?

**Comment by AkshayChordiya** [comment] 2018-03-21 03:36
You need to add `NEWS_API_KEY` in your `gradle.properties` for Gradle to build.
Kindly go through the following [steps](https://github.com/AkshayChordiya/android-arch-news-sample#steps-to-run) to generate key for your app.

Android Studio should have made the file for you if not then manually create the file and add this line:

NEWS_API_KEY = "YOUR_API_KEY"

Duplicate of #1

**Closed by AkshayChordiya** 2018-03-21 03:36 UTC

**Comment by Catherinelhl** [comment] 2018-03-28 17:13
Thank you!
